//
// Created by gorod on 10.04.2026.
//

#ifndef CMAKESFMLPROJECT_PINACTIONNAMES_H
#define CMAKESFMLPROJECT_PINACTIONNAMES_H

enum class PinActionName {
  BUZZER, LEFT_FRONT_WHEEL_FORWARD, LEFT_FRONT_WHEEL_BACKWARD, RIGHT_FRONT_WHEEL_FORWARD, RIGHT_FRONT_WHEEL_BACKWARD,
  LEFT_REAR_WHEEL_FORWARD, LEFT_REAR_WHEEL_BACKWARD, RIGHT_REAR_WHEEL_FORWARD, RIGHT_REAR_WHEEL_BACKWARD,
  
};

#endif //CMAKESFMLPROJECT_PINACTIONNAMES_H