//
// Created by Alexander on 11.04.2026.
//

#ifndef CMAKESFMLPROJECT_INPUTCONSTANTS_H
#define CMAKESFMLPROJECT_INPUTCONSTANTS_H

enum class InputConstans{

    /*BUZZER,
    GRIPPER_PRESS,
    GRIPPER_RELEASE,
    GRIPPER_UP,
    GRIPPER_DOWN,
    MOVE_FORWARD_DIGITAL,
    MOVE_BACKWARD_DIGITAL,
    ROTATE_CW_DIGITAL,
    ROTATE_CCW_DIGITAL
*/
    BUZZER_DIGITAL,
    GRIPPER_PRESS,
    GRIPPER_RELEASE,
    GRIPPER_UP,
    GRIPPER_DOWN,
    MOVE_FORWARD_DIGITAL,
    MOVE_BACKWARD_DIGITAL,
    ROTATE_CW_DIGITAL,
    ROTATE_CCW_DIGITAL,
    MOVEMENT_DIGITAL,
    ROTATION_DIGITAL,
    MOVEMENT_ANALOG,
    ROTATION_ANALOG,
    BUZZER_ANALOG,
    PAUSE,
    SWITCH_OFF

};

#endif //CMAKESFMLPROJECT_INPUTCONSTANTS_H
