//
// Created by Alexander on 09.04.2026.
//

#ifndef CMAKESFMLPROJECT_GLOBALCOMMANDPREFIX_H
#define CMAKESFMLPROJECT_GLOBALCOMMANDPREFIX_H


enum class LocalCommandPrefix {
    PREFIX_MOVEMENT_FORWARD, PREFIX_MOVEMENT_BACKWARD, PREFIX_ROTATION_CW, PREFIX_ROTATION_CCW, PREFIX_NOISE_DIGITAL, PREFIX_NOISE_ANALOG, NO_DATA

    //FORWARD, BACKWARD, LEFT, RIGHT, NOISE, NO_DATA


    , PREFIX_SWITCH_OFF, PREFIX_PAUSE, PREFIX_MOVEMENT_ANALOG, PREFIX_ROTATION_ANALOG
};


#endif //CMAKESFMLPROJECT_GLOBALCOMMANDPREFIX_H
