//
// Created by gorod on 14.04.2026.
//

#ifndef CMAKESFMLPROJECT_MECHANICALCONSTANTS_H
#define CMAKESFMLPROJECT_MECHANICALCONSTANTS_H

constexpr float WHEELS_BASE_WIDTH = 174;
constexpr float WHEELS_BASE_LENGTH = 245;


#endif //CMAKESFMLPROJECT_MECHANICALCONSTANTS_H